name: mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  dio: ^5.11.1
  flutter:
    sdk: flutter
  image_picker: ^1.2.4
  intl: ^0.20.3
  mask_text_input_formatter: ^2.9.0
  shared_preferences: ^2.5.6
  url_launcher: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
