"""make_shift_branch_nullable

Revision ID: 000b6a0f9f1d
Revises: e5f6a7b8c9d0
Create Date: 2026-03-19 10:43:20.636058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '000b6a0f9f1d'
down_revision: Union[str, None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_transfer_items_id'), table_name='stock_transfer_items')
    op.drop_table('stock_transfer_items')
    op.drop_index(op.f('ix_stock_transfers_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_number'), table_name='stock_transfers')
    op.drop_table('stock_transfers')
    op.drop_constraint(op.f('inventory_counts_number_key'), 'inventory_counts', type_='unique')
    op.drop_index(op.f('ix_inventory_counts_number'), table_name='inventory_counts')
    op.create_index(op.f('ix_inventory_counts_number'), 'inventory_counts', ['number'], unique=True)
    op.alter_column('shifts', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shifts', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_inventory_counts_number'), table_name='inventory_counts')
    op.create_index(op.f('ix_inventory_counts_number'), 'inventory_counts', ['number'], unique=False)
    op.create_unique_constraint(op.f('inventory_counts_number_key'), 'inventory_counts', ['number'], postgresql_nulls_not_distinct=False)
    op.create_table('stock_transfers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('from_warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'in_transit', 'received', 'cancelled', name='transferstatus'), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confirmed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('stock_transfers_confirmed_by_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('stock_transfers_created_by_fkey')),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], name=op.f('stock_transfers_from_warehouse_id_fkey')),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], name=op.f('stock_transfers_to_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_transfers_pkey'))
    )
    op.create_index(op.f('ix_stock_transfers_number'), 'stock_transfers', ['number'], unique=True)
    op.create_index(op.f('ix_stock_transfers_id'), 'stock_transfers', ['id'], unique=False)
    op.create_table('stock_transfer_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transfer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('stock_transfer_items_product_id_fkey')),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], name=op.f('stock_transfer_items_transfer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_transfer_items_pkey'))
    )
    op.create_index(op.f('ix_stock_transfer_items_id'), 'stock_transfer_items', ['id'], unique=False)
    # ### end Alembic commands ###
