"""Add branch relationships

Revision ID: 09735e25bc45
Revises: 84a37ca12068
Create Date: 2026-03-14 17:07:15.050916

"""
from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa  # type: ignore
from sqlalchemy.dialects import postgresql  # type: ignore

revision: str = '09735e25bc45'
down_revision: Union[str, None] = '84a37ca12068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_status_enum = postgresql.ENUM('active', 'inactive', 'blocked', name='userstatus', create_type=False)
    user_status_enum.create(op.get_bind(), checkfirst=True)

    # Create warehouses table if it doesn't exist
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'warehouses' not in inspector.get_table_names():
        op.create_table('warehouses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('type', sa.Enum('main', 'transit', 'returns', 'shop', name='warehousetype'), nullable=True),
        sa.Column('address', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)

    op.add_column('users', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('status', sa.Enum('active', 'inactive', 'blocked', name='userstatus'), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'director', 'manager', 'cashier', 'warehouse', 'accountant', name='userrole'),
               nullable=True)
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['id'])
    op.drop_column('users', 'is_active')
    op.add_column('warehouses', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'warehouses', 'branches', ['branch_id'], ['id'])
    op.drop_column('warehouses', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.drop_column('warehouses', 'branch_id')
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'director', 'manager', 'cashier', 'warehouse', 'accountant', name='userrole'),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('users', 'status')
    op.drop_column('users', 'branch_id')
    # ### end Alembic commands ###
