"""add_company_org_code_region_district

Revision ID: 0ab0f63edf62
Revises: 08e432b58c66
Create Date: 2026-03-25 13:26:11.004053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0ab0f63edf62'
down_revision: Union[str, None] = '08e432b58c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agents_code_key'), 'agents', type_='unique')
    op.add_column('companies', sa.Column('org_code', sa.String(length=10), nullable=True))
    op.add_column('companies', sa.Column('region', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('district', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_companies_org_code'), 'companies', ['org_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_org_code'), table_name='companies')
    op.drop_column('companies', 'district')
    op.drop_column('companies', 'region')
    op.drop_column('companies', 'org_code')
    op.create_unique_constraint(op.f('agents_code_key'), 'agents', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
