"""Add Phase 4 Expansion CRM and Currencies Models

Revision ID: 3417c59a5ce9
Revises: 09735e25bc45
Create Date: 2026-03-15 10:48:50.594933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3417c59a5ce9'
down_revision: Union[str, None] = '09735e25bc45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    op.add_column('sales', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('exchange_rate', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('sales', sa.Column('loyalty_points_earned', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('loyalty_points_used', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'currencies', ['currency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'loyalty_points_used')
    op.drop_column('sales', 'loyalty_points_earned')
    op.drop_column('sales', 'exchange_rate')
    op.drop_column('sales', 'currency_id')
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.drop_table('currencies')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
