"""add_mxik_parent_code_unit_id_to_products

Revision ID: 36f7cf7bb6d5
Revises: 2e4c73ca0e32
Create Date: 2026-06-11 11:49:59.768424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '36f7cf7bb6d5'
down_revision: Union[str, None] = '2e4c73ca0e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('products', sa.Column('mxik_code', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('parent_code', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_mxik_code'), 'products', ['mxik_code'], unique=False)
    conn = op.get_bind()
    has_fk = conn.execute(sa.text(
        "SELECT EXISTS (SELECT 1 FROM information_schema.table_constraints "
        "WHERE table_name = 'products' AND constraint_name = 'products_customer_id_fkey')"
    )).scalar()
    if has_fk:
        op.drop_constraint(op.f('products_customer_id_fkey'), 'products', type_='foreignkey')
    has_col = conn.execute(sa.text(
        "SELECT EXISTS (SELECT 1 FROM information_schema.columns "
        "WHERE table_name = 'products' AND column_name = 'customer_id')"
    )).scalar()
    if has_col:
        op.drop_column('products', 'customer_id')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('products_customer_id_fkey'), 'products', 'customers', ['customer_id'], ['id'])
    op.drop_index(op.f('ix_products_mxik_code'), table_name='products')
    op.drop_column('products', 'unit_id')
    op.drop_column('products', 'parent_code')
    op.drop_column('products', 'mxik_code')
    # ### end Alembic commands ###
