"""add_server_defaults_to_customers

Revision ID: 37e71f86c9d7
Revises: 02311083a87c
Create Date: 2026-06-08 15:58:36.315173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '37e71f86c9d7'
down_revision: Union[str, None] = '02311083a87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
