"""add_purchased_at_to_companies

Revision ID: 3ca49e4cb8a5
Revises: 80e2bebe2d02
Create Date: 2026-06-15 14:10:44.327986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3ca49e4cb8a5'
down_revision: Union[str, None] = '80e2bebe2d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from sqlalchemy import text
    conn = op.get_bind()

    # user_wallets jadvali va indexini xavfsiz o'chirish
    conn.execute(text("DROP INDEX IF EXISTS ix_user_wallets_user;"))
    conn.execute(text("DROP TABLE IF EXISTS user_wallets;"))

    # bot_sessions jadvali va indexini xavfsiz o'chirish
    conn.execute(text("DROP INDEX IF EXISTS ix_bot_sessions_chat_id;"))
    conn.execute(text("DROP TABLE IF EXISTS bot_sessions;"))

    # companies.purchased_at ustunini xavfsiz qo'shish
    conn.execute(text(
        "ALTER TABLE companies ADD COLUMN IF NOT EXISTS purchased_at TIMESTAMP;"
    ))

    # companies dan payme ustunlarini xavfsiz o'chirish
    for col in ('payme_is_test', 'payme_merchant_id', 'payme_secret_key'):
        conn.execute(text(
            f"ALTER TABLE companies DROP COLUMN IF EXISTS {col};"
        ))

    # kassa_movements indexlarini xavfsiz o'chirish
    for idx in ('ix_kassa_movements_company', 'ix_kassa_movements_created', 'ix_kassa_movements_wallet'):
        conn.execute(text(f"DROP INDEX IF EXISTS {idx};"))

    # kassa_sessions indexlarini xavfsiz o'chirish
    for idx in ('ix_kassa_sessions_company', 'ix_kassa_sessions_wallet'):
        conn.execute(text(f"DROP INDEX IF EXISTS {idx};"))

    # payme_transactions indexlarini xavfsiz o'chirish
    for idx in ('ix_payme_txn_company', 'ix_payme_txn_payme_id'):
        conn.execute(text(f"DROP INDEX IF EXISTS {idx};"))

    # sales.wallet_id foreign key va ustunini xavfsiz o'chirish
    conn.execute(text("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.table_constraints
                WHERE table_name='sales' AND constraint_name='sales_wallet_id_fkey'
            ) THEN
                ALTER TABLE sales DROP CONSTRAINT sales_wallet_id_fkey;
            END IF;
        END $$;
    """))
    conn.execute(text("ALTER TABLE sales DROP COLUMN IF EXISTS wallet_id;"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('sales_wallet_id_fkey'), 'sales', 'wallets', ['wallet_id'], ['id'])
    op.create_index(op.f('ix_payme_txn_payme_id'), 'payme_transactions', ['payme_id'], unique=True)
    op.create_index(op.f('ix_payme_txn_company'), 'payme_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_kassa_sessions_wallet'), 'kassa_sessions', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_kassa_sessions_company'), 'kassa_sessions', ['company_id'], unique=False)
    op.create_index(op.f('ix_kassa_movements_wallet'), 'kassa_movements', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_kassa_movements_created'), 'kassa_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_kassa_movements_company'), 'kassa_movements', ['company_id'], unique=False)
    op.add_column('companies', sa.Column('payme_secret_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_merchant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_is_test', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_column('companies', 'purchased_at')
    op.create_table('bot_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('step', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('temp_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bot_sessions_pkey'))
    )
    op.create_index(op.f('ix_bot_sessions_chat_id'), 'bot_sessions', ['chat_id'], unique=False)
    op.create_table('user_wallets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_wallets_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('user_wallets_wallet_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_wallets_pkey')),
    sa.UniqueConstraint('user_id', 'wallet_id', name=op.f('user_wallets_user_id_wallet_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_wallets_user'), 'user_wallets', ['user_id'], unique=False)
    # ### end Alembic commands ###
