"""add_spic_and_labels_to_products

Revision ID: 44b8ebad9615
Revises: 75c0ddbd8542
Create Date: 2026-07-04 10:11:22.468618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '44b8ebad9615'
down_revision: Union[str, None] = '75c0ddbd8542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_bot_sessions_chat_id")
    op.execute("DROP TABLE IF EXISTS bot_sessions")
    op.execute("ALTER TABLE companies DROP COLUMN IF EXISTS payme_is_test")
    op.execute("ALTER TABLE companies DROP COLUMN IF EXISTS payme_secret_key")
    op.execute("ALTER TABLE companies DROP COLUMN IF EXISTS payme_merchant_id")
    op.execute("DROP INDEX IF EXISTS ix_kassa_movements_company")
    op.execute("DROP INDEX IF EXISTS ix_kassa_movements_created")
    op.execute("DROP INDEX IF EXISTS ix_kassa_movements_wallet")
    op.execute("DROP INDEX IF EXISTS ix_kassa_sessions_company")
    op.execute("DROP INDEX IF EXISTS ix_kassa_sessions_wallet")
    op.execute("DROP INDEX IF EXISTS ix_payme_txn_company")
    op.execute("DROP INDEX IF EXISTS ix_payme_txn_payme_id")
    op.add_column('products', sa.Column('mxik_code', sa.String(length=20), nullable=True))
    op.execute("DROP INDEX IF EXISTS ix_products_spic")
    op.create_index(op.f('ix_products_mxik_code'), 'products', ['mxik_code'], unique=False)
    op.execute("ALTER TABLE products DROP COLUMN IF EXISTS spic")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('spic', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.execute("DROP INDEX IF EXISTS ix_products_mxik_code")
    op.create_index(op.f('ix_products_spic'), 'products', ['spic'], unique=False)
    op.execute("ALTER TABLE products DROP COLUMN IF EXISTS mxik_code")
    op.create_index(op.f('ix_payme_txn_payme_id'), 'payme_transactions', ['payme_id'], unique=True)
    op.create_index(op.f('ix_payme_txn_company'), 'payme_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_kassa_sessions_wallet'), 'kassa_sessions', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_kassa_sessions_company'), 'kassa_sessions', ['company_id'], unique=False)
    op.create_index(op.f('ix_kassa_movements_wallet'), 'kassa_movements', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_kassa_movements_created'), 'kassa_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_kassa_movements_company'), 'kassa_movements', ['company_id'], unique=False)
    op.add_column('companies', sa.Column('payme_merchant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_secret_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_is_test', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.create_table('bot_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('step', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('temp_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bot_sessions_pkey'))
    )
    op.create_index(op.f('ix_bot_sessions_chat_id'), 'bot_sessions', ['chat_id'], unique=False)
    # ### end Alembic commands ###
