"""create customer_prices table

Revision ID: 45e5b2298a37
Revises: 46499e514f46
Create Date: 2026-06-07 12:52:45.405021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '45e5b2298a37'
down_revision: Union[str, None] = '46499e514f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'product_id', name='up_customer_product')
    )
    op.create_index(op.f('ix_customer_prices_id'), 'customer_prices', ['id'], unique=False)
    op.drop_index(op.f('ix_bot_sessions_chat_id'), table_name='bot_sessions')
    op.drop_table('bot_sessions')
    op.drop_index(op.f('ix_user_wallets_user'), table_name='user_wallets')
    op.drop_table('user_wallets')
    op.drop_column('companies', 'payme_merchant_id')
    op.drop_column('companies', 'payme_is_test')
    op.drop_column('companies', 'payme_secret_key')
    op.drop_index(op.f('ix_kassa_movements_company'), table_name='kassa_movements')
    op.drop_index(op.f('ix_kassa_movements_created'), table_name='kassa_movements')
    op.drop_index(op.f('ix_kassa_movements_wallet'), table_name='kassa_movements')
    op.drop_index(op.f('ix_kassa_sessions_company'), table_name='kassa_sessions')
    op.drop_index(op.f('ix_kassa_sessions_wallet'), table_name='kassa_sessions')
    op.drop_index(op.f('ix_payme_txn_company'), table_name='payme_transactions')
    op.drop_index(op.f('ix_payme_txn_payme_id'), table_name='payme_transactions')
    op.drop_constraint(op.f('sales_wallet_id_fkey'), 'sales', type_='foreignkey')
    op.drop_column('sales', 'wallet_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('sales_wallet_id_fkey'), 'sales', 'wallets', ['wallet_id'], ['id'])
    op.create_index(op.f('ix_payme_txn_payme_id'), 'payme_transactions', ['payme_id'], unique=True)
    op.create_index(op.f('ix_payme_txn_company'), 'payme_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_kassa_sessions_wallet'), 'kassa_sessions', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_kassa_sessions_company'), 'kassa_sessions', ['company_id'], unique=False)
    op.create_index(op.f('ix_kassa_movements_wallet'), 'kassa_movements', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_kassa_movements_created'), 'kassa_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_kassa_movements_company'), 'kassa_movements', ['company_id'], unique=False)
    op.add_column('companies', sa.Column('payme_secret_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_is_test', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_merchant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_table('user_wallets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_wallets_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('user_wallets_wallet_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_wallets_pkey')),
    sa.UniqueConstraint('user_id', 'wallet_id', name=op.f('user_wallets_user_id_wallet_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_wallets_user'), 'user_wallets', ['user_id'], unique=False)
    op.create_table('bot_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('step', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('temp_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bot_sessions_pkey'))
    )
    op.create_index(op.f('ix_bot_sessions_chat_id'), 'bot_sessions', ['chat_id'], unique=False)
    op.drop_index(op.f('ix_customer_prices_id'), table_name='customer_prices')
    op.drop_table('customer_prices')
    # ### end Alembic commands ###
