"""remove unique constraint from currency code

Revision ID: 47ee2009b90c
Revises: 84033d7124e4
Create Date: 2026-03-27 13:01:30.157432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '47ee2009b90c'
down_revision: Union[str, None] = '84033d7124e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('currencies_code_key'), 'currencies', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('currencies_code_key'), 'currencies', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
