"""Add bin_locations

Revision ID: 4b197855415f
Revises: 47ee2009b90c
Create Date: 2026-03-27 13:45:58.521802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b197855415f'
down_revision: Union[str, None] = '47ee2009b90c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
