"""add_is_active_to_currency

Revision ID: 5f1b62a7c853
Revises: c2d3e4f5a6b7
Create Date: 2026-03-17 16:32:06.649241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5f1b62a7c853'
down_revision: Union[str, None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bin_locations_code'), table_name='bin_locations')
    op.drop_index(op.f('ix_bin_locations_id'), table_name='bin_locations')
    op.drop_table('bin_locations')
    op.add_column('currencies', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currencies', 'is_active')
    op.create_table('bin_locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bin_locations_pkey'))
    )
    op.create_index(op.f('ix_bin_locations_id'), 'bin_locations', ['id'], unique=False)
    op.create_index(op.f('ix_bin_locations_code'), 'bin_locations', ['code'], unique=True)
    # ### end Alembic commands ###
