"""add sms_verifications table

Revision ID: 5f42fc9c4e27
Revises: 6d0cf4b3bce5
Create Date: 2026-10-10 11:49:22.494923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5f42fc9c4e27'
down_revision: Union[str, None] = '6d0cf4b3bce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_verifications_id'), 'sms_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_sms_verifications_phone'), 'sms_verifications', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sms_verifications_phone'), table_name='sms_verifications')
    op.drop_index(op.f('ix_sms_verifications_id'), table_name='sms_verifications')
    op.drop_table('sms_verifications')
    # ### end Alembic commands ###
