"""add_product_type_and_product_conversions

Revision ID: 6eedca5e439f
Revises: j4k5l6m7n8o9
Create Date: 2026-05-22 14:36:32.053909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6eedca5e439f'
down_revision: Union[str, None] = 'j4k5l6m7n8o9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sell_product_id', sa.Integer(), nullable=False),
    sa.Column('source_product_id', sa.Integer(), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['sell_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_conversions_id'), 'product_conversions', ['id'], unique=False)
    op.create_index(op.f('ix_product_conversions_sell_product_id'), 'product_conversions', ['sell_product_id'], unique=True)
    op.create_index(op.f('ix_product_conversions_source_product_id'), 'product_conversions', ['source_product_id'], unique=False)
    op.drop_index(op.f('ix_bot_sessions_chat_id'), table_name='bot_sessions')
    op.drop_table('bot_sessions')
    op.drop_column('companies', 'payme_is_test')
    op.drop_column('companies', 'payme_merchant_id')
    op.drop_column('companies', 'payme_secret_key')
    op.drop_index(op.f('ix_payme_txn_company'), table_name='payme_transactions')
    op.drop_index(op.f('ix_payme_txn_payme_id'), table_name='payme_transactions')
    op.add_column('products', sa.Column('product_type', sa.String(length=10), nullable=False, server_default='stock'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_type')
    op.create_index(op.f('ix_payme_txn_payme_id'), 'payme_transactions', ['payme_id'], unique=True)
    op.create_index(op.f('ix_payme_txn_company'), 'payme_transactions', ['company_id'], unique=False)
    op.add_column('companies', sa.Column('payme_secret_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_merchant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_is_test', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.create_table('bot_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('step', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('temp_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bot_sessions_pkey'))
    )
    op.create_index(op.f('ix_bot_sessions_chat_id'), 'bot_sessions', ['chat_id'], unique=False)
    op.drop_index(op.f('ix_product_conversions_source_product_id'), table_name='product_conversions')
    op.drop_index(op.f('ix_product_conversions_sell_product_id'), table_name='product_conversions')
    op.drop_index(op.f('ix_product_conversions_id'), table_name='product_conversions')
    op.drop_table('product_conversions')
    # ### end Alembic commands ###
