"""add_spic_and_labels_to_products

Revision ID: 75c0ddbd8542
Revises: b55e026ed7b1
Create Date: 2026-07-04 09:44:41.210893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '75c0ddbd8542'
down_revision: Union[str, None] = 'b55e026ed7b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('spic', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('labels', sa.JSON(), nullable=True))
    op.alter_column('products', 'cost_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=16, scale=4),
               existing_nullable=False)
    op.alter_column('products', 'wholesale_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=16, scale=4),
               existing_nullable=True)
    op.alter_column('products', 'sale_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=16, scale=4),
               existing_nullable=False)
    op.execute("DROP INDEX IF EXISTS ix_products_mxik_code")
    op.create_index(op.f('ix_products_spic'), 'products', ['spic'], unique=False)
    op.execute("ALTER TABLE products DROP COLUMN IF EXISTS mxik_code")
    op.alter_column('sale_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=16, scale=4),
               existing_nullable=False)
    op.alter_column('sale_items', 'cost_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=16, scale=4),
               existing_nullable=False)
    op.alter_column('sale_items', 'discount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=16, scale=4),
               existing_nullable=True)
    op.alter_column('sale_items', 'subtotal',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('sales', 'total_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('sales', 'discount_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('sales', 'paid_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('sales', 'paid_cash',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('sales', 'paid_card',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('sales', 'paid_cashback',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('sms_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sms_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('sales', 'paid_cashback',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('sales', 'paid_card',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('sales', 'paid_cash',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('sales', 'paid_amount',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('sales', 'discount_amount',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('sales', 'total_amount',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('sale_items', 'subtotal',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('sale_items', 'discount',
               existing_type=sa.Numeric(precision=16, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('sale_items', 'cost_price',
               existing_type=sa.Numeric(precision=16, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('sale_items', 'unit_price',
               existing_type=sa.Numeric(precision=16, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.add_column('products', sa.Column('mxik_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.execute("DROP INDEX IF EXISTS ix_products_spic")
    op.create_index(op.f('ix_products_mxik_code'), 'products', ['mxik_code'], unique=False)
    op.alter_column('products', 'sale_price',
               existing_type=sa.Numeric(precision=16, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('products', 'wholesale_price',
               existing_type=sa.Numeric(precision=16, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'cost_price',
               existing_type=sa.Numeric(precision=16, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.execute("ALTER TABLE products DROP COLUMN IF EXISTS labels")
    op.execute("ALTER TABLE products DROP COLUMN IF EXISTS spic")
    # ### end Alembic commands ###
