"""add_balance_to_company

Revision ID: 84033d7124e4
Revises: dd768a649862
Create Date: 2026-03-27 10:22:24.198565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '84033d7124e4'
down_revision: Union[str, None] = 'dd768a649862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_transfer_items_id'), table_name='stock_transfer_items')
    op.drop_table('stock_transfer_items')
    op.drop_index(op.f('ix_bin_locations_code'), table_name='bin_locations')
    op.drop_index(op.f('ix_bin_locations_id'), table_name='bin_locations')
    op.drop_table('bin_locations')
    op.drop_index(op.f('ix_stock_transfers_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_number'), table_name='stock_transfers')
    op.drop_table('stock_transfers')
    op.add_column('companies', sa.Column('balance', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False))
    op.drop_column('purchase_orders', 'payment_type')
    op.drop_column('purchase_orders', 'paid_amount')
    op.drop_column('purchase_orders', 'discount_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('discount_amount', sa.NUMERIC(precision=14, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('paid_amount', sa.NUMERIC(precision=14, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('payment_type', sa.VARCHAR(length=20), server_default=sa.text("'cash'::character varying"), autoincrement=False, nullable=True))
    op.drop_column('companies', 'balance')
    op.create_table('stock_transfers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('from_warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'in_transit', 'received', 'cancelled', name='transferstatus'), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confirmed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('stock_transfers_confirmed_by_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('stock_transfers_created_by_fkey')),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], name=op.f('stock_transfers_from_warehouse_id_fkey')),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], name=op.f('stock_transfers_to_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_transfers_pkey'))
    )
    op.create_index(op.f('ix_stock_transfers_number'), 'stock_transfers', ['number'], unique=True)
    op.create_index(op.f('ix_stock_transfers_id'), 'stock_transfers', ['id'], unique=False)
    op.create_table('bin_locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bin_locations_pkey'))
    )
    op.create_index(op.f('ix_bin_locations_id'), 'bin_locations', ['id'], unique=False)
    op.create_index(op.f('ix_bin_locations_code'), 'bin_locations', ['code'], unique=True)
    op.create_table('stock_transfer_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transfer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('stock_transfer_items_product_id_fkey')),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], name=op.f('stock_transfer_items_transfer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_transfer_items_pkey'))
    )
    op.create_index(op.f('ix_stock_transfer_items_id'), 'stock_transfer_items', ['id'], unique=False)
    # ### end Alembic commands ###
