"""add_balance_to_company

Revision ID: 84033d7124e4
Revises: dd768a649862
Create Date: 2026-03-27 10:22:24.198565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '84033d7124e4'
down_revision: Union[str, None] = 'dd768a649862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _drop_table_if_exists(inspector, table_name, indexes=None):
    tables = inspector.get_table_names()
    if table_name not in tables:
        return
    if indexes:
        existing_idx = [i['name'] for i in inspector.get_indexes(table_name)]
        for idx in indexes:
            if idx in existing_idx:
                op.drop_index(op.f(idx), table_name=table_name)
    op.drop_table(table_name)


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    _drop_table_if_exists(inspector, 'stock_transfer_items', ['ix_stock_transfer_items_id'])
    _drop_table_if_exists(inspector, 'bin_locations', ['ix_bin_locations_code', 'ix_bin_locations_id'])
    _drop_table_if_exists(inspector, 'stock_transfers', ['ix_stock_transfers_id', 'ix_stock_transfers_number'])

    comp_cols = [c['name'] for c in inspector.get_columns('companies')]
    if 'balance' not in comp_cols:
        op.add_column('companies', sa.Column('balance', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False))

    if 'purchase_orders' in inspector.get_table_names():
        po_cols = [c['name'] for c in inspector.get_columns('purchase_orders')]
        for col in ('payment_type', 'paid_amount', 'discount_amount'):
            if col in po_cols:
                op.drop_column('purchase_orders', col)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('discount_amount', sa.NUMERIC(precision=14, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('paid_amount', sa.NUMERIC(precision=14, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('payment_type', sa.VARCHAR(length=20), server_default=sa.text("'cash'::character varying"), autoincrement=False, nullable=True))
    op.drop_column('companies', 'balance')
    op.create_table('stock_transfers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('from_warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'in_transit', 'received', 'cancelled', name='transferstatus'), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confirmed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('stock_transfers_confirmed_by_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('stock_transfers_created_by_fkey')),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], name=op.f('stock_transfers_from_warehouse_id_fkey')),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], name=op.f('stock_transfers_to_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_transfers_pkey'))
    )
    op.create_index(op.f('ix_stock_transfers_number'), 'stock_transfers', ['number'], unique=True)
    op.create_index(op.f('ix_stock_transfers_id'), 'stock_transfers', ['id'], unique=False)
    op.create_table('bin_locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bin_locations_pkey'))
    )
    op.create_index(op.f('ix_bin_locations_id'), 'bin_locations', ['id'], unique=False)
    op.create_index(op.f('ix_bin_locations_code'), 'bin_locations', ['code'], unique=True)
    op.create_table('stock_transfer_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transfer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('stock_transfer_items_product_id_fkey')),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], name=op.f('stock_transfer_items_transfer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_transfer_items_pkey'))
    )
    op.create_index(op.f('ix_stock_transfer_items_id'), 'stock_transfer_items', ['id'], unique=False)
    # ### end Alembic commands ###
