"""add_warehouse_id_to_sales

Revision ID: 93e705f35484
Revises: cff2b4b823e0
Create Date: 2026-03-25 18:36:49.304554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '93e705f35484'
down_revision: Union[str, None] = 'cff2b4b823e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'warehouses', ['warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'warehouse_id')
    # ### end Alembic commands ###
