"""add customer_id to sales

Revision ID: 94e706f35485
Revises: 93e705f35484
Create Date: 2026-03-25 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e706f35485'
down_revision: Union[str, None] = '93e705f35484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_sales_customer', 'sales', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sales_customer', 'sales', type_='foreignkey')
    op.drop_column('sales', 'customer_id')
    # ### end Alembic commands ###
