"""add_super_admin_role

Revision ID: 9f366b630e80
Revises: 000b6a0f9f1d
Create Date: 2026-03-24 20:03:56.161373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9f366b630e80'
down_revision: Union[str, None] = '000b6a0f9f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
