"""add admin_tg_bots table

Revision ID: a91b29c54b5e
Revises: b31c2062044d
Create Date: 2026-07-13 11:40:56.555230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a91b29c54b5e'
down_revision: Union[str, None] = 'b31c2062044d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    bind = op.get_bind()
    insp = inspect(bind)
    
    if 'admin_tg_bots' not in insp.get_table_names():
        has_enum = bind.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'roleenum'")).scalar()
        if not has_enum:
            # Create the enum type manually if it doesn't exist
            bind.execute(sa.text("CREATE TYPE roleenum AS ENUM ('direktor', 'manager', 'admin')"))
            
        op.create_table('admin_tg_bots',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('tg_id', sa.String(length=20), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=False),
        sa.Column('full_name', sa.String(length=255), nullable=True),
        sa.Column('role', postgresql.ENUM('direktor', 'manager', 'admin', name='roleenum', create_type=False), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tg_id'),
        sa.UniqueConstraint('tg_id', 'company_id', name='uq_admin_tg_bot_user_company')
        )
    # op.create_table('admin_tg_bots',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('tg_id', sa.String(length=20), nullable=False),
    # sa.Column('phone', sa.String(length=20), nullable=False),
    # sa.Column('full_name', sa.String(length=255), nullable=True),
    # sa.Column('role', sa.Enum('direktor', 'manager', 'admin', name='roleenum'), nullable=False),
    # sa.Column('company_id', sa.Integer(), nullable=False),
    # sa.Column('is_active', sa.Boolean(), nullable=True),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    # sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    # sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('tg_id'),
    # sa.UniqueConstraint('tg_id', 'company_id', name='uq_admin_tg_bot_user_company')
    # )
    # op.drop_index(op.f('ix_bot_sessions_chat_id'), table_name='bot_sessions', if_exists=True)
    # op.drop_table('bot_sessions')
    # op.drop_column('companies', 'payme_merchant_id')
    # op.drop_column('companies', 'payme_is_test')
    # op.drop_column('companies', 'payme_secret_key')
    # op.drop_index(op.f('ix_kassa_movements_company'), table_name='kassa_movements')
    # op.drop_index(op.f('ix_kassa_movements_created'), table_name='kassa_movements')
    # op.drop_index(op.f('ix_kassa_movements_wallet'), table_name='kassa_movements')
    # op.drop_index(op.f('ix_kassa_sessions_company'), table_name='kassa_sessions')
    # op.drop_index(op.f('ix_kassa_sessions_wallet'), table_name='kassa_sessions')
    # op.drop_index(op.f('ix_payme_txn_company'), table_name='payme_transactions')
    # op.drop_index(op.f('ix_payme_txn_payme_id'), table_name='payme_transactions')
    # # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_payme_txn_payme_id'), 'payme_transactions', ['payme_id'], unique=True)
    op.create_index(op.f('ix_payme_txn_company'), 'payme_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_kassa_sessions_wallet'), 'kassa_sessions', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_kassa_sessions_company'), 'kassa_sessions', ['company_id'], unique=False)
    op.create_index(op.f('ix_kassa_movements_wallet'), 'kassa_movements', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_kassa_movements_created'), 'kassa_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_kassa_movements_company'), 'kassa_movements', ['company_id'], unique=False)
    op.add_column('companies', sa.Column('payme_secret_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_is_test', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_merchant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_table('bot_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('step', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('temp_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bot_sessions_pkey'))
    )
    op.create_index(op.f('ix_bot_sessions_chat_id'), 'bot_sessions', ['chat_id'], unique=False)
    op.drop_table('admin_tg_bots', if_exists=True)
    # ### end Alembic commands ###
