"""add_supplier_bank_rating_fields

Revision ID: aec747063e38
Revises: 5f1b62a7c853
Create Date: 2026-03-17 16:46:46.816101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aec747063e38'
down_revision: Union[str, None] = '5f1b62a7c853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('bank_name', sa.String(length=200), nullable=True))
    op.add_column('suppliers', sa.Column('bank_account', sa.String(length=30), nullable=True))
    op.add_column('suppliers', sa.Column('bank_mfo', sa.String(length=10), nullable=True))
    op.add_column('suppliers', sa.Column('contract_number', sa.String(length=100), nullable=True))
    op.add_column('suppliers', sa.Column('contract_date', sa.DateTime(), nullable=True))
    op.add_column('suppliers', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('suppliers', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'notes')
    op.drop_column('suppliers', 'rating')
    op.drop_column('suppliers', 'contract_date')
    op.drop_column('suppliers', 'contract_number')
    op.drop_column('suppliers', 'bank_mfo')
    op.drop_column('suppliers', 'bank_account')
    op.drop_column('suppliers', 'bank_name')
    # ### end Alembic commands ###
