"""add_currency_to_kassa_tables

Revision ID: b6f04b67b8fb
Revises: bb491d7ee91e
Create Date: 2026-07-24 11:31:02.296204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b6f04b67b8fb'
down_revision: Union[str, None] = 'bb491d7ee91e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_sessions_chat_id'), table_name='bot_sessions')
    op.drop_table('bot_sessions')
    op.drop_column('companies', 'payme_merchant_id')
    op.drop_column('companies', 'payme_is_test')
    op.drop_column('companies', 'payme_secret_key')
    op.drop_index(op.f('ix_company_bots_company_id'), table_name='company_bots')
    
    # Add currency columns as nullable first, then update existing data, then make NOT NULL
    op.add_column('kassa_movements', sa.Column('currency', sa.String(length=3), nullable=True))
    op.execute("UPDATE kassa_movements SET currency = 'UZS' WHERE currency IS NULL")
    op.alter_column('kassa_movements', 'currency', nullable=False)
    
    op.drop_index(op.f('ix_kassa_movements_company'), table_name='kassa_movements')
    op.drop_index(op.f('ix_kassa_movements_created'), table_name='kassa_movements')
    op.drop_index(op.f('ix_kassa_movements_wallet'), table_name='kassa_movements')
    
    op.add_column('kassa_sessions', sa.Column('currency', sa.String(length=3), nullable=True))
    op.execute("UPDATE kassa_sessions SET currency = 'UZS' WHERE currency IS NULL")
    op.alter_column('kassa_sessions', 'currency', nullable=False)
    
    op.drop_index(op.f('ix_kassa_sessions_company'), table_name='kassa_sessions')
    op.drop_index(op.f('ix_kassa_sessions_wallet'), table_name='kassa_sessions')
    op.drop_index(op.f('ix_payme_txn_company'), table_name='payme_transactions')
    op.drop_index(op.f('ix_payme_txn_payme_id'), table_name='payme_transactions')
    
    op.add_column('wallets', sa.Column('currency', sa.String(length=3), nullable=True))
    op.execute("UPDATE wallets SET currency = 'UZS' WHERE currency IS NULL")
    op.alter_column('wallets', 'currency', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'currency')
    op.create_index(op.f('ix_payme_txn_payme_id'), 'payme_transactions', ['payme_id'], unique=True)
    op.create_index(op.f('ix_payme_txn_company'), 'payme_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_kassa_sessions_wallet'), 'kassa_sessions', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_kassa_sessions_company'), 'kassa_sessions', ['company_id'], unique=False)
    op.drop_column('kassa_sessions', 'currency')
    op.create_index(op.f('ix_kassa_movements_wallet'), 'kassa_movements', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_kassa_movements_created'), 'kassa_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_kassa_movements_company'), 'kassa_movements', ['company_id'], unique=False)
    op.drop_column('kassa_movements', 'currency')
    op.create_index(op.f('ix_company_bots_company_id'), 'company_bots', ['company_id'], unique=False)
    op.add_column('companies', sa.Column('payme_secret_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_is_test', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_merchant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_table('bot_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('step', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('temp_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bot_sessions_pkey'))
    )
    op.create_index(op.f('ix_bot_sessions_chat_id'), 'bot_sessions', ['chat_id'], unique=False)
    # ### end Alembic commands ###
