"""add_expiry_date_to_products

Revision ID: bb491d7ee91e
Revises: df8f6f8cd2d3
Create Date: 2026-07-24 11:04:49.142430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bb491d7ee91e'
down_revision: Union[str, None] = 'df8f6f8cd2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
