"""Add expiry_date to po_items

Revision ID: cc0719a3b1c2
Revises: 4d3a6c308ab6
Create Date: 2026-08-13 11:24:43.564573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cc0719a3b1c2'
down_revision: Union[str, None] = '4d3a6c308ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batches', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('companies', 'payme_secret_key')
    op.drop_column('companies', 'payme_merchant_id')
    op.drop_column('companies', 'payme_is_test')
    op.drop_index(op.f('ix_company_bots_company_id'), table_name='company_bots')
    op.alter_column('inventory_count_items', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_kassa_movements_company'), table_name='kassa_movements')
    op.drop_index(op.f('ix_kassa_movements_created'), table_name='kassa_movements')
    op.drop_index(op.f('ix_kassa_movements_wallet'), table_name='kassa_movements')
    op.drop_index(op.f('ix_kassa_sessions_company'), table_name='kassa_sessions')
    op.drop_index(op.f('ix_kassa_sessions_wallet'), table_name='kassa_sessions')
    op.drop_index(op.f('ix_payme_txn_company'), table_name='payme_transactions')
    op.drop_index(op.f('ix_payme_txn_payme_id'), table_name='payme_transactions')
    op.add_column('po_items', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    op.alter_column('po_items', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sale_item_batches', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sale_items', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stock_levels', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stock_movements', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stock_transfer_items', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_transfer_items', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stock_movements', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stock_levels', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sale_items', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sale_item_batches', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('po_items', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('po_items', 'expiry_date')
    op.create_index(op.f('ix_payme_txn_payme_id'), 'payme_transactions', ['payme_id'], unique=True)
    op.create_index(op.f('ix_payme_txn_company'), 'payme_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_kassa_sessions_wallet'), 'kassa_sessions', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_kassa_sessions_company'), 'kassa_sessions', ['company_id'], unique=False)
    op.create_index(op.f('ix_kassa_movements_wallet'), 'kassa_movements', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_kassa_movements_created'), 'kassa_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_kassa_movements_company'), 'kassa_movements', ['company_id'], unique=False)
    op.alter_column('inventory_count_items', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_company_bots_company_id'), 'company_bots', ['company_id'], unique=False)
    op.add_column('companies', sa.Column('payme_is_test', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_merchant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_secret_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.alter_column('batches', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
