"""add company_id to all models

Revision ID: cff2b4b823e0
Revises: f0a73a05900d
Create Date: 2026-03-25 14:45:23.718043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cff2b4b823e0'
down_revision: Union[str, None] = 'f0a73a05900d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _add_company_id(inspector, table_name):
    """Jadval mavjud bo'lsa va company_id yo'q bo'lsa qo'shadi."""
    tables = inspector.get_table_names()
    if table_name not in tables:
        return
    cols = [c['name'] for c in inspector.get_columns(table_name)]
    if 'company_id' not in cols:
        op.add_column(table_name, sa.Column('company_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, table_name, 'companies', ['company_id'], ['id'])


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    for tbl in [
        'batches', 'categories', 'currencies', 'customers',
        'expense_categories', 'expenses', 'products', 'purchase_orders',
        'sales', 'shifts', 'suppliers', 'transactions', 'users', 'warehouses',
    ]:
        _add_company_id(inspector, tbl)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.drop_column('warehouses', 'company_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'company_id')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'company_id')
    op.drop_constraint(None, 'shifts', type_='foreignkey')
    op.drop_column('shifts', 'company_id')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'company_id')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'company_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'company_id')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'company_id')
    op.drop_constraint(None, 'expense_categories', type_='foreignkey')
    op.drop_column('expense_categories', 'company_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'company_id')
    op.drop_constraint(None, 'currencies', type_='foreignkey')
    op.drop_column('currencies', 'company_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'company_id')
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.drop_column('batches', 'company_id')
    # ### end Alembic commands ###
