"""add company_id to all models

Revision ID: cff2b4b823e0
Revises: f0a73a05900d
Create Date: 2026-03-25 14:45:23.718043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cff2b4b823e0'
down_revision: Union[str, None] = 'f0a73a05900d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'batches', 'companies', ['company_id'], ['id'])
    op.add_column('categories', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'companies', ['company_id'], ['id'])
    op.add_column('currencies', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'currencies', 'companies', ['company_id'], ['id'])
    op.add_column('customers', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customers', 'companies', ['company_id'], ['id'])
    op.add_column('expense_categories', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expense_categories', 'companies', ['company_id'], ['id'])
    op.add_column('expenses', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'companies', ['company_id'], ['id'])
    op.add_column('products', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'companies', ['company_id'], ['id'])
    op.add_column('purchase_orders', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase_orders', 'companies', ['company_id'], ['id'])
    op.add_column('sales', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'companies', ['company_id'], ['id'])
    op.add_column('shifts', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shifts', 'companies', ['company_id'], ['id'])
    op.add_column('suppliers', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'suppliers', 'companies', ['company_id'], ['id'])
    op.add_column('transactions', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'companies', ['company_id'], ['id'])
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    op.add_column('warehouses', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'warehouses', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.drop_column('warehouses', 'company_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'company_id')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'company_id')
    op.drop_constraint(None, 'shifts', type_='foreignkey')
    op.drop_column('shifts', 'company_id')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'company_id')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'company_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'company_id')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'company_id')
    op.drop_constraint(None, 'expense_categories', type_='foreignkey')
    op.drop_column('expense_categories', 'company_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'company_id')
    op.drop_constraint(None, 'currencies', type_='foreignkey')
    op.drop_column('currencies', 'company_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'company_id')
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.drop_column('batches', 'company_id')
    # ### end Alembic commands ###
