"""change_loyalty_points_to_bigint

Revision ID: change_loyalty_points_to_bigint
Revises: b6f04b67b8fb
Create Date: 2026-07-24 10:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'change_loyalty_points_to_bigint'
down_revision: Union[str, None] = '7ab8bbc6f685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'loyalty_points',
                    existing_type=sa.Integer(),
                    type_=sa.BigInteger())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'loyalty_points',
                    existing_type=sa.BigInteger(),
                    type_=sa.Integer())
    # ### end Alembic commands ###
