"""Add batch FIFO columns

Revision ID: dd768a649862
Revises: 94e706f35485
Create Date: 2026-03-26 20:47:17.794324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dd768a649862'
down_revision: Union[str, None] = '94e706f35485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('customers_card_number_key'), 'customers', type_='unique')
    op.drop_constraint(op.f('customers_tg_chat_id_key'), 'customers', type_='unique')
    op.create_index(op.f('ix_customers_card_number'), 'customers', ['card_number'], unique=True)
    op.create_index(op.f('ix_customers_tg_chat_id'), 'customers', ['tg_chat_id'], unique=True)
    op.drop_index(op.f('ix_sale_item_batches_batch_id'), table_name='sale_item_batches')
    op.drop_index(op.f('ix_sale_item_batches_sale_item_id'), table_name='sale_item_batches')
    op.create_index(op.f('ix_sale_item_batches_id'), 'sale_item_batches', ['id'], unique=False)
    op.drop_constraint(op.f('sale_item_batches_batch_id_fkey'), 'sale_item_batches', type_='foreignkey')
    op.drop_constraint(op.f('sale_item_batches_sale_item_id_fkey'), 'sale_item_batches', type_='foreignkey')
    op.create_foreign_key(None, 'sale_item_batches', 'sale_items', ['sale_item_id'], ['id'])
    op.create_foreign_key(None, 'sale_item_batches', 'batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale_item_batches', type_='foreignkey')
    op.drop_constraint(None, 'sale_item_batches', type_='foreignkey')
    op.create_foreign_key(op.f('sale_item_batches_sale_item_id_fkey'), 'sale_item_batches', 'sale_items', ['sale_item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('sale_item_batches_batch_id_fkey'), 'sale_item_batches', 'batches', ['batch_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_sale_item_batches_id'), table_name='sale_item_batches')
    op.create_index(op.f('ix_sale_item_batches_sale_item_id'), 'sale_item_batches', ['sale_item_id'], unique=False)
    op.create_index(op.f('ix_sale_item_batches_batch_id'), 'sale_item_batches', ['batch_id'], unique=False)
    op.drop_index(op.f('ix_customers_tg_chat_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_card_number'), table_name='customers')
    op.create_unique_constraint(op.f('customers_tg_chat_id_key'), 'customers', ['tg_chat_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('customers_card_number_key'), 'customers', ['card_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
