"""Add batch FIFO columns

Revision ID: dd768a649862
Revises: 94e706f35485
Create Date: 2026-03-26 20:47:17.794324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dd768a649862'
down_revision: Union[str, None] = '94e706f35485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    # customers constraint/index o'zgarishi
    existing_uq = [c['name'] for c in inspector.get_unique_constraints('customers')]
    if 'customers_card_number_key' in existing_uq:
        op.drop_constraint(op.f('customers_card_number_key'), 'customers', type_='unique')
    if 'customers_tg_chat_id_key' in existing_uq:
        op.drop_constraint(op.f('customers_tg_chat_id_key'), 'customers', type_='unique')
    existing_idx = [i['name'] for i in inspector.get_indexes('customers')]
    cust_cols = [c['name'] for c in inspector.get_columns('customers')]
    if 'card_number' in cust_cols and 'ix_customers_card_number' not in existing_idx:
        op.create_index(op.f('ix_customers_card_number'), 'customers', ['card_number'], unique=True)
    if 'tg_chat_id' in cust_cols and 'ix_customers_tg_chat_id' not in existing_idx:
        op.create_index(op.f('ix_customers_tg_chat_id'), 'customers', ['tg_chat_id'], unique=True)

    # sale_item_batches faqat mavjud bo'lsa o'zgartir
    if 'sale_item_batches' in tables:
        sib_idx = [i['name'] for i in inspector.get_indexes('sale_item_batches')]
        if 'ix_sale_item_batches_batch_id' in sib_idx:
            op.drop_index(op.f('ix_sale_item_batches_batch_id'), table_name='sale_item_batches')
        if 'ix_sale_item_batches_sale_item_id' in sib_idx:
            op.drop_index(op.f('ix_sale_item_batches_sale_item_id'), table_name='sale_item_batches')
        if 'ix_sale_item_batches_id' not in sib_idx:
            op.create_index(op.f('ix_sale_item_batches_id'), 'sale_item_batches', ['id'], unique=False)
        sib_fk = [f['name'] for f in inspector.get_foreign_keys('sale_item_batches')]
        if 'sale_item_batches_batch_id_fkey' in sib_fk:
            op.drop_constraint(op.f('sale_item_batches_batch_id_fkey'), 'sale_item_batches', type_='foreignkey')
        if 'sale_item_batches_sale_item_id_fkey' in sib_fk:
            op.drop_constraint(op.f('sale_item_batches_sale_item_id_fkey'), 'sale_item_batches', type_='foreignkey')
        op.create_foreign_key(None, 'sale_item_batches', 'sale_items', ['sale_item_id'], ['id'])
        op.create_foreign_key(None, 'sale_item_batches', 'batches', ['batch_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale_item_batches', type_='foreignkey')
    op.drop_constraint(None, 'sale_item_batches', type_='foreignkey')
    op.create_foreign_key(op.f('sale_item_batches_sale_item_id_fkey'), 'sale_item_batches', 'sale_items', ['sale_item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('sale_item_batches_batch_id_fkey'), 'sale_item_batches', 'batches', ['batch_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_sale_item_batches_id'), table_name='sale_item_batches')
    op.create_index(op.f('ix_sale_item_batches_sale_item_id'), 'sale_item_batches', ['sale_item_id'], unique=False)
    op.create_index(op.f('ix_sale_item_batches_batch_id'), 'sale_item_batches', ['batch_id'], unique=False)
    op.drop_index(op.f('ix_customers_tg_chat_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_card_number'), table_name='customers')
    op.create_unique_constraint(op.f('customers_tg_chat_id_key'), 'customers', ['tg_chat_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('customers_card_number_key'), 'customers', ['card_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
