"""add_expiry_date_to_products

Revision ID: e7ec73f8ddae
Revises: a91b29c54b5e
Create Date: 2026-07-24 10:48:04.052723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e7ec73f8ddae'
down_revision: Union[str, None] = 'a91b29c54b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_sessions_chat_id'), table_name='bot_sessions')
    op.drop_table('bot_sessions')
    op.drop_index(op.f('idx_user_wallets_user_id'), table_name='user_wallets')
    op.drop_index(op.f('idx_user_wallets_wallet_id'), table_name='user_wallets')
    op.drop_table('user_wallets')
    op.drop_table('admin_tg_bots')
    op.drop_column('companies', 'payme_merchant_id')
    op.drop_column('companies', 'payme_is_test')
    op.drop_column('companies', 'payme_secret_key')
    op.drop_index(op.f('ix_company_bots_company_id'), table_name='company_bots')
    op.drop_index(op.f('ix_kassa_movements_company'), table_name='kassa_movements')
    op.drop_index(op.f('ix_kassa_movements_created'), table_name='kassa_movements')
    op.drop_index(op.f('ix_kassa_movements_wallet'), table_name='kassa_movements')
    op.drop_index(op.f('ix_kassa_sessions_company'), table_name='kassa_sessions')
    op.drop_index(op.f('ix_kassa_sessions_wallet'), table_name='kassa_sessions')
    op.drop_index(op.f('ix_payme_txn_company'), table_name='payme_transactions')
    op.drop_index(op.f('ix_payme_txn_payme_id'), table_name='payme_transactions')
    op.add_column('products', sa.Column('expiry_data', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'expiry_data')
    op.create_index(op.f('ix_payme_txn_payme_id'), 'payme_transactions', ['payme_id'], unique=True)
    op.create_index(op.f('ix_payme_txn_company'), 'payme_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_kassa_sessions_wallet'), 'kassa_sessions', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_kassa_sessions_company'), 'kassa_sessions', ['company_id'], unique=False)
    op.create_index(op.f('ix_kassa_movements_wallet'), 'kassa_movements', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_kassa_movements_created'), 'kassa_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_kassa_movements_company'), 'kassa_movements', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_bots_company_id'), 'company_bots', ['company_id'], unique=False)
    op.add_column('companies', sa.Column('payme_secret_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_is_test', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_merchant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_table('admin_tg_bots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('direktor', 'manager', 'admin', name='roleenum'), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('admin_tg_bots_company_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_tg_bots_pkey')),
    sa.UniqueConstraint('tg_id', 'company_id', name=op.f('uq_admin_tg_bot_user_company'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('tg_id', name=op.f('admin_tg_bots_tg_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('user_wallets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_wallets_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('user_wallets_wallet_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_wallets_pkey')),
    sa.UniqueConstraint('user_id', 'wallet_id', name=op.f('user_wallets_user_id_wallet_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_user_wallets_wallet_id'), 'user_wallets', ['wallet_id'], unique=False)
    op.create_index(op.f('idx_user_wallets_user_id'), 'user_wallets', ['user_id'], unique=False)
    op.create_table('bot_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('step', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('temp_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bot_sessions_pkey'))
    )
    op.create_index(op.f('ix_bot_sessions_chat_id'), 'bot_sessions', ['chat_id'], unique=False)
    # ### end Alembic commands ###
