"""add_company_agent_id

Revision ID: f0a73a05900d
Revises: 0ab0f63edf62
Create Date: 2026-03-25 14:03:42.889067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f0a73a05900d'
down_revision: Union[str, None] = '0ab0f63edf62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'companies', 'agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'agent_id')
    # ### end Alembic commands ###
