"""add_variants_and_attributes_phase1

Revision ID: f8d0a8c76f91
Revises: fffb6a6fd84e
Create Date: 2026-08-13 09:16:16.063942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f8d0a8c76f91'
down_revision: Union[str, None] = 'fffb6a6fd84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attributes_company_id'), 'attributes', ['company_id'], unique=False)
    op.create_index(op.f('ix_attributes_id'), 'attributes', ['id'], unique=False)
    op.create_table('attribute_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attribute_values_attribute_id'), 'attribute_values', ['attribute_id'], unique=False)
    op.create_index(op.f('ix_attribute_values_id'), 'attribute_values', ['id'], unique=False)
    op.create_table('variant_attribute_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('attribute_value_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_value_id'], ['attribute_values.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variant_attribute_values_attribute_value_id'), 'variant_attribute_values', ['attribute_value_id'], unique=False)
    op.create_index(op.f('ix_variant_attribute_values_id'), 'variant_attribute_values', ['id'], unique=False)
    op.create_index(op.f('ix_variant_attribute_values_variant_id'), 'variant_attribute_values', ['variant_id'], unique=False)
    op.add_column('batches', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_batches_variant_id'), 'batches', ['variant_id'], unique=False)
    op.create_foreign_key(None, 'batches', 'product_variants', ['variant_id'], ['id'])
    op.drop_column('companies', 'payme_merchant_id')
    op.drop_column('companies', 'payme_is_test')
    op.drop_column('companies', 'payme_secret_key')
    op.drop_index(op.f('ix_company_bots_company_id'), table_name='company_bots')
    op.add_column('inventory_count_items', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory_count_items', 'product_variants', ['variant_id'], ['id'])
    op.drop_index(op.f('ix_kassa_movements_company'), table_name='kassa_movements')
    op.drop_index(op.f('ix_kassa_movements_created'), table_name='kassa_movements')
    op.drop_index(op.f('ix_kassa_movements_wallet'), table_name='kassa_movements')
    op.drop_index(op.f('ix_kassa_sessions_company'), table_name='kassa_sessions')
    op.drop_index(op.f('ix_kassa_sessions_wallet'), table_name='kassa_sessions')
    op.drop_index(op.f('ix_payme_txn_company'), table_name='payme_transactions')
    op.drop_index(op.f('ix_payme_txn_payme_id'), table_name='payme_transactions')
    op.add_column('po_items', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'po_items', 'product_variants', ['variant_id'], ['id'])
    op.add_column('sale_item_batches', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sale_item_batches', 'product_variants', ['variant_id'], ['id'])
    op.add_column('sale_items', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sale_items', 'product_variants', ['variant_id'], ['id'])
    op.add_column('stock_levels', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stock_levels_variant_id'), 'stock_levels', ['variant_id'], unique=False)
    op.create_foreign_key(None, 'stock_levels', 'product_variants', ['variant_id'], ['id'])
    op.add_column('stock_movements', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock_movements', 'product_variants', ['variant_id'], ['id'])
    op.add_column('stock_transfer_items', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock_transfer_items', 'product_variants', ['variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_transfer_items', type_='foreignkey')
    op.drop_column('stock_transfer_items', 'variant_id')
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_column('stock_movements', 'variant_id')
    op.drop_constraint(None, 'stock_levels', type_='foreignkey')
    op.drop_index(op.f('ix_stock_levels_variant_id'), table_name='stock_levels')
    op.drop_column('stock_levels', 'variant_id')
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.drop_column('sale_items', 'variant_id')
    op.drop_constraint(None, 'sale_item_batches', type_='foreignkey')
    op.drop_column('sale_item_batches', 'variant_id')
    op.drop_constraint(None, 'po_items', type_='foreignkey')
    op.drop_column('po_items', 'variant_id')
    op.create_index(op.f('ix_payme_txn_payme_id'), 'payme_transactions', ['payme_id'], unique=True)
    op.create_index(op.f('ix_payme_txn_company'), 'payme_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_kassa_sessions_wallet'), 'kassa_sessions', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_kassa_sessions_company'), 'kassa_sessions', ['company_id'], unique=False)
    op.create_index(op.f('ix_kassa_movements_wallet'), 'kassa_movements', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_kassa_movements_created'), 'kassa_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_kassa_movements_company'), 'kassa_movements', ['company_id'], unique=False)
    op.drop_constraint(None, 'inventory_count_items', type_='foreignkey')
    op.drop_column('inventory_count_items', 'variant_id')
    op.create_index(op.f('ix_company_bots_company_id'), 'company_bots', ['company_id'], unique=False)
    op.add_column('companies', sa.Column('payme_secret_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_is_test', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_merchant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.drop_index(op.f('ix_batches_variant_id'), table_name='batches')
    op.drop_column('batches', 'variant_id')
    op.drop_index(op.f('ix_variant_attribute_values_variant_id'), table_name='variant_attribute_values')
    op.drop_index(op.f('ix_variant_attribute_values_id'), table_name='variant_attribute_values')
    op.drop_index(op.f('ix_variant_attribute_values_attribute_value_id'), table_name='variant_attribute_values')
    op.drop_table('variant_attribute_values')
    op.drop_index(op.f('ix_attribute_values_id'), table_name='attribute_values')
    op.drop_index(op.f('ix_attribute_values_attribute_id'), table_name='attribute_values')
    op.drop_table('attribute_values')
    op.drop_index(op.f('ix_attributes_id'), table_name='attributes')
    op.drop_index(op.f('ix_attributes_company_id'), table_name='attributes')
    op.drop_table('attributes')
    # ### end Alembic commands ###
