"""add customer_id to products

Revision ID: fa56aaa5e6f4
Revises: df9132535f4b
Create Date: 2026-06-06 18:41:55.384436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fa56aaa5e6f4'
down_revision: Union[str, None] = 'df9132535f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(conn, table_name):
    return conn.execute(sa.text(
        "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = :t)"
    ), {"t": table_name}).scalar()

def _column_exists(conn, table_name, column_name):
    return conn.execute(sa.text(
        "SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = :t AND column_name = :c)"
    ), {"t": table_name, "c": column_name}).scalar()

def _index_exists(conn, index_name):
    return conn.execute(sa.text(
        "SELECT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = :i)"
    ), {"i": index_name}).scalar()

def _fk_exists(conn, table_name, fk_name):
    return conn.execute(sa.text(
        "SELECT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_name = :t AND constraint_name = :c)"
    ), {"t": table_name, "c": fk_name}).scalar()


def upgrade() -> None:
    conn = op.get_bind()

    if _table_exists(conn, 'bot_sessions'):
        if _index_exists(conn, 'ix_bot_sessions_chat_id'):
            op.drop_index(op.f('ix_bot_sessions_chat_id'), table_name='bot_sessions')
        op.drop_table('bot_sessions')

    if _table_exists(conn, 'user_wallets'):
        if _index_exists(conn, 'ix_user_wallets_user'):
            op.drop_index(op.f('ix_user_wallets_user'), table_name='user_wallets')
        op.drop_table('user_wallets')

    if _column_exists(conn, 'companies', 'payme_secret_key'):
        op.drop_column('companies', 'payme_secret_key')
    if _column_exists(conn, 'companies', 'payme_is_test'):
        op.drop_column('companies', 'payme_is_test')
    if _column_exists(conn, 'companies', 'payme_merchant_id'):
        op.drop_column('companies', 'payme_merchant_id')

    for idx, tbl in [
        ('ix_kassa_movements_company', 'kassa_movements'),
        ('ix_kassa_movements_created', 'kassa_movements'),
        ('ix_kassa_movements_wallet', 'kassa_movements'),
        ('ix_kassa_sessions_company', 'kassa_sessions'),
        ('ix_kassa_sessions_wallet', 'kassa_sessions'),
        ('ix_payme_txn_company', 'payme_transactions'),
        ('ix_payme_txn_payme_id', 'payme_transactions'),
    ]:
        if _index_exists(conn, idx):
            op.drop_index(op.f(idx), table_name=tbl)

    if not _column_exists(conn, 'products', 'customer_id'):
        op.add_column('products', sa.Column('customer_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'products', 'customers', ['customer_id'], ['id'])

    if not _column_exists(conn, 'sale_items', 'warehouse_id'):
        op.add_column('sale_items', sa.Column('warehouse_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'sale_items', 'warehouses', ['warehouse_id'], ['id'])

    if not _column_exists(conn, 'sale_items', 'unit'):
        op.add_column('sale_items', sa.Column('unit', sa.String(length=20), nullable=True))

    if _column_exists(conn, 'sales', 'wallet_id'):
        if _fk_exists(conn, 'sales', 'sales_wallet_id_fkey'):
            op.drop_constraint(op.f('sales_wallet_id_fkey'), 'sales', type_='foreignkey')
        op.drop_column('sales', 'wallet_id')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('sales_wallet_id_fkey'), 'sales', 'wallets', ['wallet_id'], ['id'])
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.drop_column('sale_items', 'unit')
    op.drop_column('sale_items', 'warehouse_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'customer_id')
    op.create_index(op.f('ix_payme_txn_payme_id'), 'payme_transactions', ['payme_id'], unique=True)
    op.create_index(op.f('ix_payme_txn_company'), 'payme_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_kassa_sessions_wallet'), 'kassa_sessions', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_kassa_sessions_company'), 'kassa_sessions', ['company_id'], unique=False)
    op.create_index(op.f('ix_kassa_movements_wallet'), 'kassa_movements', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_kassa_movements_created'), 'kassa_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_kassa_movements_company'), 'kassa_movements', ['company_id'], unique=False)
    op.add_column('companies', sa.Column('payme_merchant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_is_test', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_secret_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_table('user_wallets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_wallets_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('user_wallets_wallet_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_wallets_pkey')),
    sa.UniqueConstraint('user_id', 'wallet_id', name=op.f('user_wallets_user_id_wallet_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_wallets_user'), 'user_wallets', ['user_id'], unique=False)
    op.create_table('bot_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('step', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('temp_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bot_sessions_pkey'))
    )
    op.create_index(op.f('ix_bot_sessions_chat_id'), 'bot_sessions', ['chat_id'], unique=False)
    # ### end Alembic commands ###
