"""Add marketplace agents integration

Revision ID: fc4ac3ab5d13
Revises: f7c3e9a1d586
Create Date: 2026-10-08 22:42:19.356576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fc4ac3ab5d13'
down_revision: Union[str, None] = 'f7c3e9a1d586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('original_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_image_jobs_company_created', 'image_jobs', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_image_jobs_company_token', 'image_jobs', ['company_id', 'original_token'], unique=False)
    op.create_index('ix_image_jobs_status_company', 'image_jobs', ['status', 'company_id'], unique=False)
    op.create_index('uq_image_jobs_active', 'image_jobs', ['company_id', 'original_token'], unique=True, postgresql_where=sa.text("status IN ('pending', 'processing')"), sqlite_where=sa.text("status IN ('pending', 'processing')"))
    op.create_table('marketplace_agent_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_agent_categories_category_id'), 'marketplace_agent_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_marketplace_agent_categories_id'), 'marketplace_agent_categories', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_agent_categories_user_id'), 'marketplace_agent_categories', ['user_id'], unique=False)
    op.create_table('marketplace_agent_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('income', 'payout', 'commission', 'refund', name='marketplacetransactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_agent_transactions_agent_id'), 'marketplace_agent_transactions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_marketplace_agent_transactions_id'), 'marketplace_agent_transactions', ['id'], unique=False)
    op.create_table('marketplace_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'review', 'approved', 'rejected', name='marketplaceproductstatus'), nullable=True),
    sa.Column('reject_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_products_agent_id'), 'marketplace_products', ['agent_id'], unique=False)
    op.create_index(op.f('ix_marketplace_products_category_id'), 'marketplace_products', ['category_id'], unique=False)
    op.create_index(op.f('ix_marketplace_products_company_id'), 'marketplace_products', ['company_id'], unique=False)
    op.create_index(op.f('ix_marketplace_products_id'), 'marketplace_products', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_products_status'), 'marketplace_products', ['status'], unique=False)
    op.drop_index(op.f('ix_custom_roles_company_id'), table_name='custom_roles')
    op.drop_table('custom_roles')
    op.alter_column('ai_audit_logs', 'tool_arguments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('ai_audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_ai_audit_logs_id'), 'ai_audit_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_announcements_active'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_company'), table_name='announcements')
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.add_column('companies', sa.Column('marketplace_agents_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('companies', 'payme_secret_key')
    op.drop_column('companies', 'payme_is_test')
    op.drop_column('companies', 'payme_merchant_id')
    op.drop_index(op.f('ix_company_bots_company_id'), table_name='company_bots')
    op.drop_index(op.f('ix_customers_company_id'), table_name='customers')
    op.drop_index(op.f('ix_kassa_movements_company'), table_name='kassa_movements')
    op.drop_index(op.f('ix_kassa_movements_created'), table_name='kassa_movements')
    op.drop_index(op.f('ix_kassa_movements_wallet'), table_name='kassa_movements')
    op.alter_column('kassa_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('kassa_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_kassa_sessions_company'), table_name='kassa_sessions')
    op.drop_index(op.f('ix_kassa_sessions_wallet'), table_name='kassa_sessions')
    op.drop_index(op.f('ix_payme_txn_company'), table_name='payme_transactions')
    op.drop_index(op.f('ix_payme_txn_payme_id'), table_name='payme_transactions')
    op.drop_index(op.f('ix_products_barcode_trgm'), table_name='products', postgresql_ops={'barcode': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_products_name_trgm'), table_name='products', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_products_sku_trgm'), table_name='products', postgresql_ops={'sku': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_constraint(op.f('uq_sale_deliveries_sale_id'), 'sale_deliveries', type_='unique')
    op.drop_index(op.f('ix_sale_deliveries_sale_id'), table_name='sale_deliveries')
    op.create_index(op.f('ix_sale_deliveries_sale_id'), 'sale_deliveries', ['sale_id'], unique=True)
    op.drop_index(op.f('ix_sales_cashier_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_warehouse_id'), table_name='sales')
    op.drop_index(op.f('uq_stock_product_variant_warehouse'), table_name='stock_levels')
    op.create_index(op.f('ix_stock_movements_warehouse_id'), 'stock_movements', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'user_wallets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_wallets', type_='foreignkey')
    op.drop_index(op.f('ix_stock_movements_warehouse_id'), table_name='stock_movements')
    op.create_index(op.f('uq_stock_product_variant_warehouse'), 'stock_levels', ['product_id', 'warehouse_id', sa.literal_column('COALESCE(variant_id, 0)')], unique=True)
    op.create_index(op.f('ix_sales_warehouse_id'), 'sales', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_cashier_id'), 'sales', ['cashier_id'], unique=False)
    op.drop_index(op.f('ix_sale_deliveries_sale_id'), table_name='sale_deliveries')
    op.create_index(op.f('ix_sale_deliveries_sale_id'), 'sale_deliveries', ['sale_id'], unique=False)
    op.create_unique_constraint(op.f('uq_sale_deliveries_sale_id'), 'sale_deliveries', ['sale_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_products_sku_trgm'), 'products', ['sku'], unique=False, postgresql_ops={'sku': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_products_name_trgm'), 'products', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_products_barcode_trgm'), 'products', ['barcode'], unique=False, postgresql_ops={'barcode': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_payme_txn_payme_id'), 'payme_transactions', ['payme_id'], unique=True)
    op.create_index(op.f('ix_payme_txn_company'), 'payme_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_kassa_sessions_wallet'), 'kassa_sessions', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_kassa_sessions_company'), 'kassa_sessions', ['company_id'], unique=False)
    op.alter_column('kassa_sessions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('kassa_sessions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_kassa_movements_wallet'), 'kassa_movements', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_kassa_movements_created'), 'kassa_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_kassa_movements_company'), 'kassa_movements', ['company_id'], unique=False)
    op.create_index(op.f('ix_customers_company_id'), 'customers', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_bots_company_id'), 'company_bots', ['company_id'], unique=False)
    op.add_column('companies', sa.Column('payme_merchant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_is_test', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('payme_secret_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('companies', 'marketplace_agents_enabled')
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.create_index(op.f('ix_announcements_company'), 'announcements', ['company_id'], unique=False)
    op.create_index(op.f('ix_announcements_active'), 'announcements', ['is_active'], unique=False)
    op.drop_index(op.f('ix_ai_audit_logs_id'), table_name='ai_audit_logs')
    op.alter_column('ai_audit_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_audit_logs', 'tool_arguments',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('custom_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('custom_roles_company_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('custom_roles_pkey'))
    )
    op.create_index(op.f('ix_custom_roles_company_id'), 'custom_roles', ['company_id'], unique=False)
    op.drop_index(op.f('ix_marketplace_products_status'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_id'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_company_id'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_category_id'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_agent_id'), table_name='marketplace_products')
    op.drop_table('marketplace_products')
    op.drop_index(op.f('ix_marketplace_agent_transactions_id'), table_name='marketplace_agent_transactions')
    op.drop_index(op.f('ix_marketplace_agent_transactions_agent_id'), table_name='marketplace_agent_transactions')
    op.drop_table('marketplace_agent_transactions')
    op.drop_index(op.f('ix_marketplace_agent_categories_user_id'), table_name='marketplace_agent_categories')
    op.drop_index(op.f('ix_marketplace_agent_categories_id'), table_name='marketplace_agent_categories')
    op.drop_index(op.f('ix_marketplace_agent_categories_category_id'), table_name='marketplace_agent_categories')
    op.drop_table('marketplace_agent_categories')
    op.drop_index('uq_image_jobs_active', table_name='image_jobs', postgresql_where=sa.text("status IN ('pending', 'processing')"), sqlite_where=sa.text("status IN ('pending', 'processing')"))
    op.drop_index('ix_image_jobs_status_company', table_name='image_jobs')
    op.drop_index('ix_image_jobs_company_token', table_name='image_jobs')
    op.drop_index('ix_image_jobs_company_created', table_name='image_jobs')
    op.drop_table('image_jobs')
    # ### end Alembic commands ###
