"""Add marketplace agents integration

Revision ID: fc4ac3ab5d13
Revises: f7c3e9a1d586
Create Date: 2026-10-08 22:42:19.356576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fc4ac3ab5d13'
down_revision: Union[str, None] = 'f7c3e9a1d586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_agent_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_agent_categories_category_id'), 'marketplace_agent_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_marketplace_agent_categories_id'), 'marketplace_agent_categories', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_agent_categories_user_id'), 'marketplace_agent_categories', ['user_id'], unique=False)
    op.create_table('marketplace_agent_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('income', 'payout', 'commission', 'refund', name='marketplacetransactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_agent_transactions_agent_id'), 'marketplace_agent_transactions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_marketplace_agent_transactions_id'), 'marketplace_agent_transactions', ['id'], unique=False)
    op.create_table('marketplace_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'review', 'approved', 'rejected', name='marketplaceproductstatus'), nullable=True),
    sa.Column('reject_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_products_agent_id'), 'marketplace_products', ['agent_id'], unique=False)
    op.create_index(op.f('ix_marketplace_products_category_id'), 'marketplace_products', ['category_id'], unique=False)
    op.create_index(op.f('ix_marketplace_products_company_id'), 'marketplace_products', ['company_id'], unique=False)
    op.create_index(op.f('ix_marketplace_products_id'), 'marketplace_products', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_products_status'), 'marketplace_products', ['status'], unique=False)
    op.add_column('companies', sa.Column('marketplace_agents_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketplace_products_status'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_id'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_company_id'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_category_id'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_agent_id'), table_name='marketplace_products')
    op.drop_table('marketplace_products')
    op.drop_index(op.f('ix_marketplace_agent_transactions_id'), table_name='marketplace_agent_transactions')
    op.drop_index(op.f('ix_marketplace_agent_transactions_agent_id'), table_name='marketplace_agent_transactions')
    op.drop_table('marketplace_agent_transactions')
    op.drop_index(op.f('ix_marketplace_agent_categories_user_id'), table_name='marketplace_agent_categories')
    op.drop_index(op.f('ix_marketplace_agent_categories_id'), table_name='marketplace_agent_categories')
    op.drop_index(op.f('ix_marketplace_agent_categories_category_id'), table_name='marketplace_agent_categories')
    op.drop_table('marketplace_agent_categories')
    op.drop_column('companies', 'marketplace_agents_enabled')
    # ### end Alembic commands ###
