export const PERMISSIONS = {
  products: { label: 'Mahsulotlar', desc: "Mahsulotlarni ko'rish va tahrirlash" },
  customers: { label: 'Mijozlar', desc: "Mijozlar ro'yxati va qarzlari" },
  sotuv: { label: 'Sotuv (POS)', desc: "POS va Chakana savdo oynasi" },
  shifts: { label: 'Smenalar', desc: "Kassir smenalarini boshqarish" },
  filiallar: { label: 'Filiallar', desc: "Filiallar o'rtasida tovar ko'chirish" },
  purchases: { label: "Xarid va Ta'minotchilar", desc: "Yangi mol kelishi va ta'minotchilar bilan hisob-kitob" },
  warehouse: { label: 'Omborxona', desc: "Ombordagi tovarlar qoldig'i va harakati" },
  operations: { label: 'Operatsiyalar', desc: "Barcha operatsiyalar (Tranzaksiyalar) tarixi" },
  finance: { label: 'Moliya', desc: "Moliyaviy ko'rsatkichlar va foyda/zarar" },
  'chiqim-tolovlar': { label: "Chiqim to'lovlar", desc: "Kassadan qilingan barcha chiqimlar" },
  'kirim-tolovlar': { label: "Kirim to'lovlar", desc: "Kassaga kiritilgan barcha kirimlar" },
  kassa: { label: 'Kassa (Hisoblar)', desc: "Hamyonlar va kassalar boshqaruvi" },
  reports: { label: 'Hisobotlar', desc: "Umumiy statistik hisobotlar va tahlillar" },
  employees: { label: 'Xodimlar', desc: "Xodimlarni qo'shish va huquqlarini sozlash" },
  settings: { label: 'Sozlamalar', desc: "Do'kon va kvitansiya sozlamalari" },
  tariflar: { label: 'Tariflar', desc: "Tizim tariflari va to'lovlar tarixi" },
};
